### ISSUE TITLE
Won't build under linux.

### ISSUE THREAD

**Issue by CyrilPaulus** [openblack/openblack#10]
Tried to build under linux but it fails.

Seems like ```exception(char const* const _Message)``` doesn't exists on linux.
So call like this will not build ```throw std::exception("no such file");```
Maybe use std::runtime_error instead ?

**Comment by handsomematt** [comment]
I'll change them to std::runtime_error, thanks :)

**Comment by CyrilPaulus** [comment]
Nice to hear :)
It think they were other issues after fixing the ```std:exception``` one, but I just gave up and booted windows.

Still linux support would be great.

**Comment by handsomematt** [comment]
should be all fixed #13
