### ISSUE TITLE
LHScriptX implementation (Land.txt & InfoScript.txt scripts)

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#11]
As well as the compiled quest files, Black & White contains another language called LHScriptX - this is used to load maps as well as define language constants and can be found in the not complete list of following files:

- Scripts/InfoScript*.txt (These are all UTF-16 files)
- Scripts/Land1/2/3/4/5.txt
- Scripts/map.txt

## Lexing Scripts

The format is very simple and is mostly implemented in [OpenBlack::LHScriptX::Lexer](https://github.com/openblack/openblack/blob/master/src/LHScriptX/Lexer.h)

An example of bits from Land1.txt:

```
VERSION(2.300000)
SET_LAND_NUMBER(1)

LOAD_LANDSCAPE(".\DATA\LANDSCAPE\Land1.lnd")

START_CAMERA_POS("1441.56,2081.76")
SET_TOWN_INFLUENCE_MULTIPLIER(1.000000)

**** Player[0] ****
REM	Citadel with 0 worship sites and 0 creature pens
REM	Towns: 1
```

And another example from InfoScript2.txt (which is in UTF-16):

```
SLONG    HELP_TEXT_LAST
HELP_TEXT_LAST =  6974

NUM_ENTRIES( HELP_TEXT_LAST )
ADD_TEXT( 0, HELP_TEXT_NARRATOR_NONE, "HELP_TEXT_NONE", "Invalid text string.")
ADD_TEXT( 0, HELP_TEXT_NARRATOR_NONE, "HELP_TEXT_VILLAGER_MALE_BANTER_SET1_01", "Work, work, work. I'm sick of it.")
```

A valid list of acceptable tokens is the following:

* An identifier: starts with `A-Za-z` and can contain `A-Za-z0-9_`
* An integer: `0-9`
* A floating point: `0-9` `.` `0-9`
* Operators: `=`, `(`, `)`, `,`
* A string: anything between two `"` as long as it's a valid character and not a new line.

Each statement is seperated by a new line and comments begin at the start of a new line with either `REM` or `****`.

**The above specification doesn't fit for info scripts that can define variables. That is todo.**

## Running Scripts

Once the scripts are tokenized, we need to provide the [script parser](https://github.com/openblack/openblack/blob/master/src/LHScriptX/Script.h) with a [command table](https://github.com/openblack/openblack/blob/master/src/LHScriptX/Command_Tables.cpp) containing all the possible commands we need to run.

There appears to be 3 main command tables LHScriptX is used with:

- [Map(.txt) Commands](https://github.com/openblack/openblack/blob/master/src/LHScriptX/Command_Tables.cpp#L35) - small set of about 20 commands, mainly responsible for loading feature scripts.
- [Feature Script Commands](https://github.com/openblack/openblack/blob/master/src/LHScriptX/Command_Tables.cpp#L61) - 105 commands responsible for placing features throughout a map.
- Info Script Commands - I don't have a command list dump, but it just seems to be `NUM_ENTRIES` and `ADD_TEXT`.

With these command tables in place, any identifiers we parse that match them should execute the functions accordingly with variable context.

**Comment by handsomematt** [comment]
If anybody has any suggestions to how I can handle lexing the UTF-16 files I'd be happy to hear. My no-brain approach would to simply be to template the lexer to accept `std::string` as well as `std::wstring` - but unsure if this would be as simple as I think it'd be.

**Comment by raffclar** [comment]
This branch incidentally contains an initial set of working LHScriptX function implementations. Going to separate it out at the weekend but worth a look.

https://github.com/raffclar/openblack/tree/entities

**Comment by michaeldkroener** [comment]
Regarding the UTF-16 file issue maybe something like https://github.com/nemtrif/utfcpp ?
