### ISSUE TITLE
Left CTRL only detected in combination with another key

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#110]
I don't know if this is specific to Linux, but I cannot move the camera down with `LCTRL` unless I press another key.

This could be due to the fact that `LCTRL` is a modifier key.

My setup is Arch Linux under gnome. My SDL version is 2.0.10.

**Comment by NeroBurner** [comment]
for me on KDE Plasma (wayland) on Arch Linux `LCTRL` works as expected. Will double check

**Comment by bwrsandman** [comment]
I figured out the cause. I had my settings to find the cursor with ctrl key.
This is a weird issue that gnome and cinnamon consume the keypress and don't forward it to SDL.

![image](https://user-images.githubusercontent.com/1013356/65498860-f2309980-debc-11e9-91a0-607b36e6ff8b.png)
