### ISSUE TITLE
More robust command line parsing

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#127]
Relating to https://github.com/openblack/openblack/pull/126#issuecomment-544281893

>Can we agree to use single `-` for one char parameters but `--` for multi? The way the code is written now, help would have to be `-help`. I prefer `--help` being help and `-help` being equivalent to `-h -e -l -p`.

Here are a few libraries. Note that it's pretty simple to just roll one out ourselves too.
* https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html
* https://github.com/cofyc/argparse
* https://github.com/hbristow/argparse
* https://github.com/p-ranav/argparse
* https://github.com/alex85k/wingetopt
* https://github.com/skandhurkat/Getopt-for-Visual-Studio
* https://github.com/skeeto/optparse
* https://github.com/bkaradzic/bx/blob/702b676ec28abc9c63942cc3d31c855adaffd4ce/include/bx/commandline.h
* https://github.com/septag/sx/blob/master/include/sx/cmdline.h
* https://github.com/jarro2783/cxxopts
* https://github.com/brofield/simpleopt
* Not boost please!

Many of these libraries haven't been updated in a while. This may be ok since a commandline parser doesn't exactly need a lot of maintenance.

**Comment by handsomematt** [comment]
thoughts on https://github.com/jarro2783/cxxopts ?

**Comment by bwrsandman** [comment]
Seems as good as the others. Would have to dive into details.

I would evaluate it based on this:
1. Size of the library
2. CMake/cmake friendly packaging
3. Auto generation of help argument (with nice formatting)
4. Activity on github (open Issues, last commit date)
5. Beauty of the api

**Comment by handsomematt** [comment]
whilst this library does have CMake and all that, I would prefer to include a small library like this as header only just to minimize on additional user dependencies

**Comment by bwrsandman** [comment]
That's what I meant by "cmake friendly packaging": single header works too.

**Comment by bwrsandman** [comment]
I'm testing https://github.com/p-ranav/argparse
Pros:
* Easy to install system wide.
* It's in vcpkg and AUR
* Easy enough methods to convert on the fly to custom types.
Cons:
* Heavy use to exceptions, and generic ones
* Printing help is limited to one function which prints to `std::cout`, no option to print to `std::cerr` if the wrong command is used.
* Prints out tabs and puts no space between help message and `[Required]`
* Odd spacing... there's no indent to the optional arguments
* Puts required arguments under "Optional Arguments"

**Comment by bwrsandman** [comment]
Testing https://github.com/jarro2783/cxxopts 

Pros:
* Easy to install system wide
* It's in the AUR and vcpkg
* Exceptions are not generic `cxxopts::option_not_exists_exception`

Cons:
* Also uses exceptions
