### ISSUE TITLE
Ocean has visible corner at horizon

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#166]
Currently the ocean has a visible corer at horizon. This is because the ocean is a quad.

![Screenshot from 2019-11-13 19-01-45](https://user-images.githubusercontent.com/1013356/68791907-95469980-064a-11ea-84b0-913fae8d4067.png)

One solution might be to scale the ocean up.
Another solution would be to a disc so that the corners are closer to 180 degrees.

**Comment by RisingDaystar** [comment]
Maybe it could be fine to just apply ,through shader, a subtle "fog effect" (with strength in relation to camera distance for example, or in relation to distance to "map boundary" ), this would also help against the edges aliasing effect, and could avoid any kind of mesh manipulation.
It might also look nice if affected by Time of Day lighting color... (hmm... the singing sailors scene comes to my head...)
As far as i have seen, this workaround seems to be used pretty often in games (especially open world-ish)

**Comment by bwrsandman** [comment]
The quad points (not uvs) could also be rotated depending on the camera orientation so that the corners are always at 45 degrees from the POV

**Comment by handsomematt** [comment]
Fixed the visible corners by expanding the water quad plane to the same dimensions as Black & White:

![image](https://user-images.githubusercontent.com/1388267/73958592-0ae79c00-4900-11ea-8a9b-a1c272a586ad.png)

This matches the "simple water" implementation, track a more advanced implementation in #186
