### ISSUE TITLE
Add Windows ARM as a supported target platform

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#174]
Would be a nice feature, Linux ARM could be done too but is less of a widely used target.

**Comment by NeroBurner** [comment]
I'd say linux arm is a bit more widespread than you think
- https://www.pine64.org/pinebook-pro/
- https://www.raspberrypi.org/
- https://www.nvidia.com/en-us/shield/

**Comment by bwrsandman** [comment]
> android

**Comment by bwrsandman** [comment]
All our VCPKG dependencies now support windows ARM, linux ARM and android ARM as part of my push for #262
