### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [openblack/openblack#18]
I think people will be more interested in testing this reimplementation and maybe collaborate with some code if you show its current state with some screenshots (even early ones!).

**Comment by raffclar** [comment]
@handsomematt Those screenshots I pm'd you a few days ago?

**Comment by handsomematt** [comment]
![Land 1](https://user-images.githubusercontent.com/1388267/63901709-b8738c80-c9fd-11e9-9d1e-da728515ac0e.png) ![Land 2](https://user-images.githubusercontent.com/1388267/63901712-bad5e680-c9fd-11e9-8000-9de22ad8054e.png)

these should be good ty, I'll add them to the readme soon

**Comment by neuromancer** [comment]
They look great, keep up the hard work!

**Comment by handsomematt** [comment]
Screenshot for bgfx README.

![openblack](https://user-images.githubusercontent.com/1388267/67631321-93c85380-f88c-11e9-9103-804807844af2.png)

**Comment by neuromancer** [comment]
This one looks better than ones you have right now! :smile:
