### ISSUE TITLE
Land 1 'The giant gate'

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#181]
![image](https://user-images.githubusercontent.com/5037244/73690042-d2fa1200-46cf-11ea-8c98-0b2070b28f32.png)
The doors are the wrong way around.

**Comment by sylcai** [comment]
![image](https://user-images.githubusercontent.com/5037244/73690393-8a8f2400-46d0-11ea-9799-8473b0015427.png)
Original Black & White screenshot as comparison

**Comment by handsomematt** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1388267/102845786-38e5aa00-4406-11eb-9a26-77df33f2383a.png)
