### ISSUE TITLE
Giant Forests do not conform to terrain / Fade out with distance

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#183]
![image](https://user-images.githubusercontent.com/5037244/73690469-b3afb480-46d0-11ea-9309-c62a80d34dbc.png)
![image](https://user-images.githubusercontent.com/5037244/73690546-e5288000-46d0-11ea-9959-1fc61c24c75d.png)
OpenBlack above
runblack below
![image](https://user-images.githubusercontent.com/5037244/73690516-d346dd00-46d0-11ea-8d79-0366f02d8677.png)

**Comment by sylcai** [comment]
The fade out is not preffered - as it 'hides' more detail. New computers can handle to show it all. Toggleble perhaps?
