### ISSUE TITLE
Small Bump & Terrain texture quality doesn't fade with distance

### ISSUE THREAD

**Issue by sylcai** [openblack/openblack#184]
![image](https://user-images.githubusercontent.com/5037244/73690628-130dc480-46d1-11ea-9c70-9cc194a2b665.png)
OpenBlack above
runblack below
![image](https://user-images.githubusercontent.com/5037244/73690684-333d8380-46d1-11ea-8ade-e33d7ac29408.png)

New behaviour is much more preffered, as it increases game fidelity

**Comment by sylcai** [comment]
The lack of falloff is causing clear visual artifacting where you can see the texture tiling: 
![image](https://user-images.githubusercontent.com/5037244/73694558-8ff06c80-46d8-11ea-8cd3-eb71e385af98.png) So perhaps a distance fader is welcomed, though it can be much further than the original black & white. (Slider perhaps for user prefference?)
![image](https://user-images.githubusercontent.com/5037244/73694633-bf06de00-46d8-11ea-8c57-2239b31510ab.png)

**Comment by handsomematt** [comment]
5a779098aed2ddbea33743aa8baa63e90d35a7f0
