### ISSUE TITLE
LOD system not implemented

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#185]
This is actually prefferable, so perhaps a toggle?

Here are gifs, as it is difficult to explain. 
runblack: https://imgur.com/KWyWjzM
openblack: https://imgur.com/dmh4Ehl

The terrain does not deform to a lower poly, the trees don't pop to their 2d cutout, and buildings do not fade with distance. Can't test with entities yet, because they don't exist.

**Comment by bwrsandman** [comment]
I don't think we need to implement the aggressive LOD of vanilla. We're targeting modern systems.
If it turns out someone wants to run it on a calculator, they're free to try and to let us know the results.
