### ISSUE TITLE
vcpkg dependency management

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#19]
Can be integrated directly into CMake to download and compile dependencies directly.

Would also help with reproducable builds on travis/appveyor

**Comment by NeroBurner** [comment]
I'd like to also propose the use of Hunter as alternative. Hunter is written in pure CMake and thus needs no other dependencies (like python)

https://docs.hunter.sh/en/latest/index.html

**Comment by handsomematt** [comment]
hunter implemented in #35
