### ISSUE TITLE
No Bowling Balls

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#193]
![image](https://user-images.githubusercontent.com/5037244/73695112-bb278b80-46d9-11ea-8daf-d652b21048b8.png)
![image](https://user-images.githubusercontent.com/5037244/73695141-cbd80180-46d9-11ea-9670-4e7d8b2fb023.png)

**Comment by captnfab** [comment]
I can see the bowling balls in the god's playground. Is this bug still relevant?

**Comment by SulpherStaer** [comment]
idk. - maybe its been fixed by now? This is a 2 year old bug, and I don't have the openblack client on my pc atm.

**Comment by bwrsandman** [comment]
Confirmed, the balls are there
![Screenshot from 2022-04-19 15-04-32](https://user-images.githubusercontent.com/1013356/164077135-5346ff45-2612-4694-b4ad-e098a7071374.png)
