### ISSUE TITLE
No Wonders

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#194]
![image](https://user-images.githubusercontent.com/5037244/73695301-1ce7f580-46da-11ea-93ea-649be718994a.png)
![image](https://user-images.githubusercontent.com/5037244/73695334-2cffd500-46da-11ea-92cb-6eb1e45b17c3.png)
![image](https://user-images.githubusercontent.com/5037244/73695375-4143d200-46da-11ea-8a64-689eb657224c.png)
![image](https://user-images.githubusercontent.com/5037244/73695401-4f91ee00-46da-11ea-969d-752ba4ea7484.png)

**Comment by bwrsandman** [comment]
We have wonders now
![Screenshot from 2022-04-19 15-05-18](https://user-images.githubusercontent.com/1013356/164077251-2d93789f-d5dc-44b9-933e-43b92c94d874.png)
