### ISSUE TITLE
Spire missing (It's a boat?)

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#195]
![image](https://user-images.githubusercontent.com/5037244/73695510-8f58d580-46da-11ea-8c68-d082b786eb3a.png)
Not only is that a boat, it also has rendering issues where it's showing its lights (with bad alpha blending to boot)
![image](https://user-images.githubusercontent.com/5037244/73695563-ae576780-46da-11ea-98d9-ed4ace522f30.png)

**Comment by bwrsandman** [comment]
The mesh is okay
![Screenshot from 2022-04-19 15-06-20](https://user-images.githubusercontent.com/1013356/164077399-4b2601ba-5c36-4ae4-bdad-cbb0c3a44e8e.png)
