### ISSUE TITLE
Soft Crash (freeze)

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#196]
![image](https://user-images.githubusercontent.com/5037244/73695723-fa0a1100-46da-11ea-8ac3-2a66d1b5b287.png)
I was looking around meshes, and when I selected Puzzle1 - it froze.

`Exception thrown at 0x00007FF6C0ED142A in openblack.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred`

**Comment by bwrsandman** [comment]
Issue no longer present

![Screenshot from 2022-04-19 15-07-19](https://user-images.githubusercontent.com/1013356/164077560-bb889cfa-a17b-4013-84ce-5113bc50bc8c.png)
