### ISSUE TITLE
Minify copyright headers

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#197]
Instead of having the GPL license at the top of each file we should just have:

```// Copyright 2018-2020 the openblack authors. See COPYING.md for legal info.```

**Comment by sylcai** [comment]
The current license is also not adjusted for openblack and still has boilerplate text near the bottom.
I think it would be simpler by setting the license with this git project, and leave it at that.

**Comment by handsomematt** [comment]
done in bb23341ff862c37cb4808ecf86ae797eff269122

copied how openrct2 does it:

```/*****************************************************************************
 * Copyright (c) 2018-2020 openblack developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/openblack/openblack
 *
 * openblack is licensed under the GNU General Public License version 3.
 *****************************************************************************/```
