### ISSUE TITLE
Windowed mode resizing window

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#211]
![image](https://user-images.githubusercontent.com/5037244/74087722-50869f00-4a8f-11ea-8316-e1c9fc028cce.png)
Resizing the window does not resize the viewport, and the upper menu also vanishes.

**Comment by FalseIlyu** [comment]
This one was solved with #373 ?

**Comment by FalseIlyu** [comment]
I believe this issue has been solved with #373 so i'm closing it;
