### ISSUE TITLE
Using latest entt causes build error due to function deprecation

### ISSUE THREAD

**Issue by zxubian** [openblack/openblack#224]
**Steps to reproduce:**

Environment: Windows 10, Microsoft Visual Studio 2019 with C++ payload & CMake toolchains

- Pull latest commit from Master branch ([1402a4f](https://github.com/openblack/openblack/commit/1402a4f8c3805f1ece832fe61b20f8b4b6d5e28c))
- Install vcpck, bgfx.cmake
- Run vcpkg install --triplet x64-windows sdl2 spdlog glm entt cxxopts
- Set CMake toochain file, bgfx_dir to respective installation directories in CMakeSettings.json screen
- Run Build/Build All

**Error Message:**

> Error (active)	E0135	class "entt::basic_registry<entt::entity>" has no member "reset"	openblack.exe (bin\openblack.exe) - x64-Debug	G:\Programming\GameDev\openblack\src\Entities\Registry.h	45	

**Suspected Cause:**

entt have renamed "::reset" to "::clear" [in this commit](https://github.com/skypjack/entt/commit/352e4576fc353faf1953bd91aa10eb53b0ad6d1a).

However, just substituting ::reset for ::clear does not solve the issue, as trying to build produces further errors:

<details>
  <summary>Errors</summary>
  

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2607	static assertion failed	G:\Programming\Gamedev\openblack\out\build\x64-Debug\openblack	G:\Soft\vcpkg\installed\x64-windows\include\entt\entity\registry.hpp	47	

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2338	The C++ Standard forbids containers of const elements because allocator<const T> is ill-formed.	G:\Programming\Gamedev\openblack\out\build\x64-Debug\openblack	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory	740	

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2535	'_Ty *std::allocator<_Ty>::address(_Ty &) noexcept const': member function already defined or declared	G:\Programming\Gamedev\openblack\out\build\x64-Debug\openblack	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory	768	

  
</details>

**Comment by handsomematt** [comment]
fixed in 5dc3716
