### ISSUE TITLE
Cannot load gamedata

### ISSUE THREAD

**Issue by JorisGoosen** [openblack/openblack#281]
So I've been trying to get openblack to load the gamedata.

I keep running into an error `Failed to open Scripts/info.dat: Info block size does not match that of GInfo: 580710 != 582022`

I first tried unpacking the data through unshield, which seemed to work reasonably enough except for some rearranging (#280).
I ran into the above error though.

So I set up a VM with WinXP and fully instaled the game there and moving it back to my linux system. I still ran into the same error though.

Do I need some other version of the gamedata? Should it be with the creature isle expansion? What am I doing wrong?

**Comment by handsomematt** [comment]
We develop based off of 1.2 which has an updated info.dat, ideally we should support retail data - however not the case right now.

**Comment by JorisGoosen** [comment]
Alright, so installing the 1.2 patch over the installed game in the VM should do the trick I guess?
I'll try it out.

**Comment by bwrsandman** [comment]
To be clear, @JorisGoosen you're using version 1.0 off of retail CD/iso?

**Comment by JorisGoosen** [comment]
Well, I didn't boot it or anything, but I assume so. I've just installed the 1.2 patch over it and after copying the now updated data openblack actually starts and shows me something!

Which means I can now have a look around.

I think it might be useful to just mention somewhere that the 1.2 version of the data is required (like in the help that is shown on running openblack for instance).

**Comment by bwrsandman** [comment]
We could modify the error message here and add a TODO to have different versions of InfoFile.
https://github.com/openblack/openblack/blob/306cbe0431c48245e55c7280dbf15343b44c4f00/src/Parsers/InfoFile.cpp#L35

**Comment by JorisGoosen** [comment]
That would work.
