### ISSUE TITLE
Tiles rendering and smooth transitions

### ISSUE THREAD

**Issue by captnfab** [openblack/openblack#3]
Currently, terrain is not smooth and we can see sharp frontier between tiles:
![display_squares](https://user-images.githubusercontent.com/4095406/48264677-a1da5580-e42a-11e8-9b0d-76abadef88fb.png)

Whereas it's supposed to look like this.
![bw1](https://user-images.githubusercontent.com/4095406/48264687-aacb2700-e42a-11e8-9853-cc5e2fcbc5da.jpg)

I wonder how it's achieved, or if it's supposed to be already working. But I've seen map editors with nice smooth terrains.

**Comment by handsomematt** [comment]
The game and map editors use immediate mode with calculated blending per
cell. We have access to this data, but we ideally don't want to use
immediate mode, therefore a creative solution using shaders needs to be
thought up.

Somehow cells need to know about their adjacent cells in order to blend
between different country textures, I'm not sure what the best approach is
for this is.

**Comment by captnfab** [comment]
I see, so for example, we could scale tiles by a 1.5× factor and do a weighted arithmetic sum (weighted with 1/r² or linear weight) of the overlapping tiles in the shaders?
If we wanted terrain to look exactly like the original, could we generate a new tileset of n⁵ tiles containing the information of their neighbors and draw those tiles instead of the raw ones? It doesn't scale well with large sets of tiles, but I assume B&W has a small set of terrains tiles.

**Comment by handsomematt** [comment]
![runblack_2018-11-15_11-42-39](https://user-images.githubusercontent.com/1388267/48591111-3d435d00-e93a-11e8-9afb-47a07f44aa5f.jpg)
![runblack_2018-11-15_15-23-56](https://user-images.githubusercontent.com/1388267/48591117-47fdf200-e93a-11e8-9ead-83e5abc1faf7.png)
![runblack_2018-11-15_15-22-03](https://user-images.githubusercontent.com/1388267/48591119-49c7b580-e93a-11e8-985b-afaca90b1143.png)

Some screenshots in game showing extreme blending and a wireframe mode of the landscape for comparison purposes. Make sure the quads are being split properly and positioned correctly etc.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/53686643-bfa53080-3d21-11e9-9fc9-990f4a482630.png)

Proper rendering implemented in 912c707f2df90e2416dcc50b91a6b3a2d8eacdcd 😄

**Comment by captnfab** [comment]
Great, this works smoothly!
