### ISSUE TITLE
Implement double click camera fly to

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#347]
In vanilla when your hand double clicks on a spot in the map, the camera will fly to just above that point.

https://user-images.githubusercontent.com/1013356/152370539-e19b3757-a7bd-40a2-a6b8-87e2aa14cf28.mp4

https://user-images.githubusercontent.com/1013356/152370725-c78cbdb1-e9f7-4d23-bb0f-2524db150bde.mp4

**Comment by tino113** [comment]
doesn't look too difficult.

**Comment by tino113** [comment]
I wonder why it picks that orientation for the first video, seems unnecessary to rotate the camera like that, what's the purpose I wonder? perhaps aligning itself with something on the map?

**Comment by tino113** [comment]
yeah that one click is odd, to be honest that looks more like a bug in original B&W, why would you click on one side of the cliff and want to see the face of the other? I think surface normals would be the way to go.

constructing a bezier curve to use as a camera path, using the camera's forward direction and the surface normal of the point should be sufficient for a first version, orient the cam to the tangent of the curve and done.. hopefully.

**Comment by bwrsandman** [comment]
@raffclar did some work on the curves for the path the camera takes in the citadel.

I know internally, vanilla uses a zoomer class for this.

**Comment by tino113** [comment]
@raffclar if you have this it might be useful
