### ISSUE TITLE
Compile issue on Windows 10 (and Linux too)

### ISSUE THREAD

**Issue by xcom169** [openblack/openblack#350]
Hello All!

Do you have any prebuilt binaries for the game? 
I can't compile it. : ( 

Windows 10 error: 
![image](https://user-images.githubusercontent.com/17802090/154478198-31d13e80-bb5e-4cf4-b90d-2d50575ffd6c.png)

On Linux I have a different error with a Wayland protocol. 

[ 89%] Linking CXX executable ../bin/openblack
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o): in function `wl_display_get_registry':
/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/wayland-client-protocol.h:1052: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o): in function `wl_registry_bind':
/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/wayland-client-protocol.h:1165: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o): in function `xdg_wm_base_destroy':
/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/xdg-shell-client-protocol.h:464: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o): in function `xdg_wm_base_pong':
/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/xdg-shell-client-protocol.h:521: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o): in function `zxdg_decoration_manager_v1_destroy':
/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/xdg-decoration-unstable-v1-client-protocol.h:177: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandvideo.c.o):/home/xcom/Documents/openblack/vcpkg/buildtrees/sdl2/x64-linux-dbg/wayland-generated-protocols/keyboard-shortcuts-inhibit-unstable-v1-client-protocol.h:218: more undefined references to `wl_proxy_marshal_flags' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/openblack.dir/build.make:1297: bin/openblack] Error 1
make[1]: *** [CMakeFiles/Makefile2:565: src/CMakeFiles/openblack.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Thanks!

**Comment by bwrsandman** [comment]
Windows: You don't have git in your PATH. Install it and make sure it's in your PATH.
Linux: What distro are you using? I have this issue and it's related to vcpkg and Arch linux. Try using Linux System Deps instead of vcpkg

**Comment by bwrsandman** [comment]
For the windows error: I think git is used for two things: getting the revision number for the title and getting imgui-flamegraph.
We should add git in our build instructions or remove the need to have it.

**Comment by xcom169** [comment]
Thanks! Installing Git helped. On Linux I use Manjaro Linux.

Do you have any tutorial for extracting game assets for the binary?

**Comment by bwrsandman** [comment]
Manjaro is Arch Linux based. You can use the Linux system deps preset. The dependencies are the same as the AUR package for openblack-git.

**Comment by bwrsandman** [comment]
Extracting the game assets is done by installing black & white and the patches up to 1.2. You can then use and copy the game data in the installed directory (in program files).

In the future we would like to support unpatched and disk/Iso single files
