### ISSUE TITLE
Move assets/game to another project

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#368]
Currently we have game data (not from the original game) in our source code.
Since it's not a great idea to mix game data and game code it would be a good idea to store it somewhere else.

Alternatively we could move it to `ci/mock` which contains scripts to generate test game resources in order to automate testing.

In any case, having those two different places for test game data is not great.

Additionally the construct scene should be tested in the screenshot job to see how it matches with

![construct Vanilla](https://user-images.githubusercontent.com/1013356/182029114-25c31d78-7c21-4375-963d-c52141b17111.png)

**Comment by handsomematt** [comment]
Another repo sounds ideal to me.
