### ISSUE TITLE
Question: FileSystem, FileStream abstractions

### ISSUE THREAD

**Issue by captnfab** [openblack/openblack#398]
I was looking at issue #377 and had a look around.

I see there are *FileSystem* and *FileStream* abstractions in `src/Common/`.
I see that code in `components/lnd/` does not use these abstractions, and uses OStream for which there is no home-made abstraction.

For what I understood, those abstractions are used for os-specific things, error handling and properly closing files. These could also be necessary if we want to implement #280.

So… What's the plan? Should we enforce using the existant FileStream for IStream in `components/lnd`? What about OStream?

**Comment by captnfab** [comment]
Ok, I understand.
In this case, to make sure that #280 can be implemented, we may have to add  some `void LNDFile::Open(std::IStream inputfile)` method, without removing the current `LNDFile::Open(const std::string& filename)` one.

**Comment by captnfab** [comment]
Ok, thanks I hadn't seen that implementation. So it's alright if components depend on each other?
I've seen src/Common/FileStream.h though. I'll have a look at all this.

**Comment by handsomematt** [comment]
The original intention of these abstractions is some files are compressed, and generally a lot of the files follow the same section based format. So it was to make it easy to use through out all components.
