### ISSUE TITLE
Bink dependency

### ISSUE THREAD

**Issue by captnfab** [openblack/openblack#4]
Hi,
I see the project now depends on some <Video/Bink.h> to play video (and thus, fails to build on my system).
Is the Bink.h part of some opensource clone of the official library? Or can it at least be obtained free of charge?
Thanks.

**Comment by handsomematt** [comment]
This was me just trying to reimplement Bink, I've removed them in 31c47d70a4e17e7a5054ee32a33e475d1fff5607

I'm not sure what the best approach to dealing with Bink videos will be, I don't really fancy using ffmpeg as an entire dependency, I've seen some other projects implement Bink video themselves but their code is heavily ingrained into their own stream classes and more.
