### ISSUE TITLE
Parse level files within the resource loader

### ISSUE THREAD

**Issue by raffclar** [openblack/openblack#400]
Once #287 is merged we need to parse the level files within the Level resource loader so that we can display additional info from `START_GAME_MESSAGE` and `ADD_GAME_MESSAGE_LINE` statements. 

If the level cannot be parsed it should be greyed out.
if the level is parsed and a START_GAME_MESSAGE statement is present then the first argument should be used in the menu select.

**Comment by bwrsandman** [comment]
The implementation should be able to work even if there are no playground maps and no Land*.txt quest maps.
This means the PR should remove Land 2-5 and Playgrounds from mock. Land 1 should stay
