### ISSUE TITLE
Don't use underscored variables

### ISSUE THREAD

**Issue by NeroBurner** [openblack/openblack#43]
https://stackoverflow.com/a/20496955

please move the underscore for private variables after the variable name
`_window` -> `window_`

the variables with underscore before the name are reserved for compiler implementors

**Comment by janisozaur** [comment]
This is a misstatement.

The [standard](http://eel.is/c++draft/lex.name#3.1) actually reads:

> Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

> Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

As such, I'm against this request.

**Comment by handsomematt** [comment]
sorry this is just my personal C++ coding preference and doesn't conflict with any standards
