### ISSUE TITLE
Distribute openblack in a Flatpak/Snap/AppImage

### ISSUE THREAD

**Issue by LeandroStanger** [openblack/openblack#50]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by NeroBurner** [comment]
How would we handle the dependency on the actual B&W game files?

**Comment by handsomematt** [comment]
> 
> 
> How would we handle the dependency on the actual B&W game files?

Same way as current I believe, point to the game directory with "-g" or at an eventual date you would have a file picker at the start of the game to find game assets if not found automatically.

**Comment by bwrsandman** [comment]
Testing out these packages would be a good start:
https://github.com/snapcore/action-build
https://github.com/snapcore/action-publish
