### ISSUE TITLE
Compilation error on Manjaro Linux with AUR package (openblack-git)

### ISSUE THREAD

**Issue by xcom169** [openblack/openblack#530]
/home/xxy/.cache/yay/openblack-git/src/openblack/src/ECS/Registry.h:78:27: error: ‘using registry = class entt::basic_registry<entt::entity>’ {aka ‘class entt::basic_registry<entt::entity>’} has no member named ‘set’; did you mean ‘get’?
   78 |                 _registry.set<RegistryContext>();
      |                           ^~~
      |                           get
/home/xxy/.cache/yay/openblack-git/src/openblack/src/ECS/Registry.h:78:46: error: expected primary-expression before ‘>’ token
   78 |                 _registry.set<RegistryContext>();
      |                                              ^
/home/xxy/.cache/yay/openblack-git/src/openblack/src/ECS/Registry.h:78:48: error: expected primary-expression before ‘)’ token
   78 |                 _registry.set<RegistryContext>();
      |                                                ^
[ 36%] Building CXX object src/CMakeFiles/openblack_lib.dir/3D/Sky.cpp.o
In file included from /home/xxy/.cache/yay/openblack-git/src/openblack/src/3D/Camera.cpp:23:
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h: At global scope:
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:39:33: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   39 |         using resources = entt::service_locator<resources::ResourcesInterface>;
      |                                 ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:40:27: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   40 |         using rng = entt::service_locator<RandomNumberManagerInterface>;
      |                           ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:41:41: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   41 |         using rendereringSystem = entt::service_locator<ecs::systems::RenderingSystemInterface>;
      |                                         ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:42:38: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   42 |         using dynamicsSystem = entt::service_locator<ecs::systems::DynamicsSystemInterface>;
      |                                      ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:43:44: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   43 |         using cameraBookmarkSystem = entt::service_locator<ecs::systems::CameraBookmarkSystemInterface>;
      |                                            ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:44:42: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   44 |         using livingActionSystem = entt::service_locator<ecs::systems::LivingActionSystemInterface>;
      |                                          ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:45:34: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   45 |         using townSystem = entt::service_locator<ecs::systems::TownSystemInterface>;
      |                                  ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/Locator.h:46:41: error: ‘service_locator’ in namespace ‘entt’ does not name a template type
   46 |         using pathfindingSystem = entt::service_locator<ecs::systems::PathfindingSystemInterface>;
      |                                         ^~~~~~~~~~~~~~~
/home/xxy/.cache/yay/openblack-git/src/openblack/src/3D/Camera.cpp: In member function ‘std::optional<openblack::ecs::components::Transform> openblack::Camera::RaycastMouseToLand()’:
/home/xxy/.cache/yay/openblack-git/src/openblack/src/3D/Camera.cpp:83:47: error: ‘openblack::Locator::dynamicsSystem’ has not been declared
   83 |         const auto& dynamicsSystem = Locator::dynamicsSystem::ref();
      |                                               ^~~~~~~~~~~~~~

**Comment by bwrsandman** [comment]
Known issue, see linked PR.
