### ISSUE TITLE
.AppImage for Linux builds

### ISSUE THREAD

**Issue by ShadowWarfare** [openblack/openblack#607]
It would be nice once released that .AppImages were to be created for the Linux-based systems and if possible a launcher to install the data files from disc and to load the game or change certain settings before launch as well. Could this be considered?

**Comment by bwrsandman** [comment]
I'm not familiar with .AppImage is it like snap packages?

**Comment by bwrsandman** [comment]
Probably can combine this issue with #50

**Comment by bwrsandman** [comment]
Launcher would be another issue.
