### ISSUE TITLE
spdlog on ubuntu 18.04 is too old

### ISSUE THREAD

**Issue by NeroBurner** [openblack/openblack#61]
the Ubuntu 18.04 build fails now because of system spdlog `libspdlog-dev/bionic 1:0.16.3-1 amd64`

on Ubuntu 18.10 we get version `libspdlog-dev/disco 1:1.3.1-1 amd64`

this means we need to use a submodule or hunter on Ubuntu 18.04 to get spdlog working

**Comment by janisozaur** [comment]
I can try porting it to a ppa

**Comment by NeroBurner** [comment]
I'll try to use Hunter like for the mingw build, but thanks for the offer

**Comment by NeroBurner** [comment]
Hunter seems to do the trick
https://travis-ci.org/NeroBurner/openblack/jobs/580616595
