### ISSUE TITLE
Update to C++23

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#656]
Requires setting https://github.com/openblack/openblack/blob/f2447f6faf02aa278738854930c5c2637f8cba22/CMakeLists.txt#L38

Steps first:
- [x] Search all TODO's related to c++ version and implement with newer c++ features such as #522 
- [x] Revisit issues related to version compatibility
- [ ] Revisit complicated templates and simplify using `concepts` (such as script to functions)
- [x] Fix errors in build
- [x] Any github action compiler download or settings

**Comment by FalseIlyu** [comment]
Current state of CI update

# Cross Compile
| Test | OS Version | Compiler Version | Pass |
|----|---------|-------------------|------|
| android-armeabi-v7a-vcpkg, ubuntu-latest | Ubuntu 22.04.3 LTS | C/C++ Clang 14.0.7 | :x: |
| android-arm64-v8a-vcpkg, ubuntu-latest | Ubuntu 22.04.3 LTS | C/C++ Clang 14.0.7 | :x: |
| android-x86-vcpkg, ubuntu-latest | Ubuntu 22.04.3 LTS | C/C++ Clang 14.0.7 | :x: |
| android-x86_64-vcpkg, ubuntu-latest | Ubuntu 22.04.3 LTS | C/C++ Clang 14.0.7 | :x: |
| x86-linux, ubuntu-latest, ninja-multi-vcpkg, sudo dpkg --add-architecture i386 | Ubuntu 22.04.3 LTS | GNU 11.4.0 | :x: |
| x86-windows, windows-latest, ninja-multi-vcpkg | Microsoft Windows Server 2022 10.0.20348 Datacenter | MSVC 19.38.33133.0 | ✔️ |
| x86-windows, windows-latest, ninja-multi-vcpkg | Microsoft Windows Server 2022 10.0.20348 Datacenter | MSVC 19.38.33133.0 | ✔️ |

**Comment by bwrsandman** [comment]
I'm going to mark this as done and any other sub task can be made into a new task
