### ISSUE TITLE
Prebuild docker images

### ISSUE THREAD

**Issue by janisozaur** [openblack/openblack#66]
Instead of building docker image for each of the build jobs, build them once and reuse. This is much faster and avoids eating lots of cycles.

Right now it of about 11 minutes spent in https://travis-ci.com/openblack/openblack/jobs/231148513, 560 seconds are spent preparing docker image, while just 75s actually building the project.

In OpenRCT2, a far bigger project, we download docker images prepared on docker hub then build the project inside utilising ccache. For openblack this could bring the total build time down to (guesstimated) 1-2 minutes, or about 85% faster.

This would also let reuse the system images to obtain reproducible builds, addressing https://github.com/openblack/openblack/issues/20 properly.

**Comment by handsomematt** [comment]
I'm completely for this, anything to keep build times down and the build process simple. :)
I don't really have the knowledge of Docker or Travis to implement this properly myself however.
