### ISSUE TITLE
LHVM: Lionhead Virtual Machine (Challenge Scripts)

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#7]
Documentation on the `chl` file-format can be found here: https://github.com/openblack/openblack/blob/master/docs/chl.md

**Comment by namgo** [comment]
I'm interested in getting involved with this project, and while the LHVM isn't an ideal place to start, it's something I find really cool. Could you say more about the status and goals for this issue?

I found the Challenge File Assembler and Challenge File Lexer that was released by one of the developers. I also saw the wiki page ( https://github.com/openblack/openblack/wiki/Challenge-File-(.chl) ) which references this. Additionally https://github.com/openblack/openblack/blob/883fd4978a31ba44cc7daff4f688a0ebb7066011/components/ScriptLibrary/docs/opcodes.md expands on this.

I'm still not quite sure about the status of integrating the VM into the game.

I'm on this project's discord now and would like to discuss this further.

-- I'm still figuring out the codebase, so I'm not quite sure what all does what, sorry if this question is just a misreading.
