### ISSUE TITLE
enum_magic requires gcc >= 9

### ISSUE THREAD

**Issue by NeroBurner** [openblack/openblack#76]
magic_enum breaks ubuntu bonic https://github.com/Neargye/magic_enum#compiler-compatibility
it requires GCC>=9

Failing Build: https://travis-ci.com/openblack/openblack/jobs/232052030

**Comment by janisozaur** [comment]
That's too bad. Personally I'd like to support the latest LTS without requiring any updated compiler. What's your suggested way of addressing that? Is magic enum a deal-breaker?

**Comment by handsomematt** [comment]
Not a deal breaker, was just something I was using to test. Better_enum didn't work so well. Will probably replace with a lookup table of strings.

**Comment by handsomematt** [comment]
fixed in c0589b485d0fa38ec1fdae0479b205220b4d29b2
