### ISSUE TITLE
Terrain Renderer

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#8]
A lot of terrain rendering was implemented in 912c707f2df90e2416dcc50b91a6b3a2d8eacdcd

However there's still the following to implement:
- [x] Noise maps to randomise the blending between textures. (3f8fb46d9462e38547a82b0ea04a9aaf9f824589)
- [x] Bump maps to add detail to the land. (d581bc7d77d82c0ebddc2a6eac3bcc5946ee95b1)
- [x] Lightmap to simulate shadows.  (b679fccf2e93e69f139357b0d354601007488392)
- [x] Small bumpmap - another smaller bumpmap is applied on landblocks very close to the camera, `smallbump.raw` (1bad414f87f7bf2ae33df4068e814983b239791b)

Documentation on the LND file format can be found here: https://github.com/openblack/openblack/blob/master/docs/lnd.md

The following are two images taken from a making of Black & White e-book, they provide a limited explanation of how the landscape is put together as well as some pretty small screenshots on their in-house editor "Leadhead".

![page1](https://user-images.githubusercontent.com/1388267/53690393-acb25080-3d61-11e9-9909-0fee7ef17763.png)
![page2](https://user-images.githubusercontent.com/1388267/53690394-acb25080-3d61-11e9-9a6c-bbc56be579be.png)

The following excerpts are the ones of most interest:

> To stop everything looking like neat layers of distinct materials we use the parameters (light/dark value) in the noise map to offset pixels in the various textures enabling us to blend adjacent textures into a more natural-looking surface.
> On top of these coloured textures we overlay a bump map.

**Comment by handsomematt** [comment]
From looking at how the game code works the gist of the noise / bump map implementations is:

* The noise bitmap is added to the altitude when picking the appropriate map material from a country: `Country->MapMaterials[altitude + noisemapValue]`
* The bumpmap value is multiplied directly with each of the texture's RGB channels.

Both map offsets map directly with the texture offsets.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/53832839-1c515700-3f7f-11e9-9fc8-4b8226298e57.png)

lightmap in b679fccf2e93e69f139357b0d354601007488392

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/60634815-37868300-9e08-11e9-8251-e364ef217207.png)

finished implementing bump maps, noise maps and small bump maps as well as fixing other inaccuracies in the terrain rendering

**Comment by aylaylay** [comment]
wow im gonna cum
