### ISSUE TITLE
Render terrain with instanced draw

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#81]
Currently, terrain is [drawn in a for loop](https://github.com/openblack/openblack/blob/71eb61dca92eff61924e1687bb12248d3667533d/src/3D/LandIsland.cpp#L203).
Each block has a uniform uploaded and is drawn before the next one.

Uploading uniforms between draw calls can stall the GPU and is not recommended.

Instead, it would be better to upload all uniforms at initialization time in a uniform array.
The draw calls should be replaced with a single instanced draw call and the uniform array should be looked up with instance id.

**Comment by FalseIlyu** [comment]
I recently tried to think on this issue again and here is a little rundown of where we are at the moment.

To use instanced call, you need to have mesh that are identical (or rather have an identical vertex buffer). The way things work in openblack each block are a distinct mesh with it's unique geometry when entering the shader.
|Current shader input | Wanted shader input|
|--------------------|-----------------|
|![image](https://github.com/openblack/openblack/assets/83550517/c45541df-2b04-471b-9380-9539641a061f)|![Mesh](https://github.com/openblack/openblack/assets/83550517/829bc428-8d4e-46aa-a0f8-37efd8bfc9e3)|

# The problem \:
In openblack each vertex are defined as follow
```
struct LandVertex
{
	glm::vec3 position;
	glm::vec3 weight;
	glm::u8vec4 firstMaterialID; 
	glm::u8vec4 secondMaterialID;
	glm::u8vec4 materialBlendCoefficient;
	glm::u8vec4 lightLevel;
	float waterAlpha;
};
```
So not only the geometry of the mesh but its material (material index, blend factor, alpha factor and luminance) are baked in the vertices and make the mesh unique in other way meaning this information must moved outside of the vertices and sent to the shader in other way.
Furthermore when compared to the regular grid in the second image, some of the triangle are rotated, this operation too must be handled by the shader.

# What to do

The work to accomplish is mostly to move the computation of the mesh from the `BuildVertexList` method in `LandBlock.cpp` to to `vs_terrain.sh` and `fs_terrain.sh`. 

To manage that the shaders are going to need to access and to iterate properly through the information contained in the `LNDCell` data structure, each block being composed of 17 x 17 cells of 4 vertex each.

To do that we'll need to either
- organise this information in a texture that we'll sample in the shader (not tried but should be the easiest)
- get this information in a constant buffer that is going to be sent as a uniform (couldn't make it work for the moment but i think it more a matter that i don't really understand bgfx well)
- get this information inside the instance buffer (couldn't make it work either, but it eliminate the need of knowing your instance id, it seems however impratical as mat4 are the large array you can use as an instance input afaik)

To use this information the shader need to know
- What block it must build, in this case each block are an instance so it is equivalent to knowing your instance id, however the instance id will need to be sent through the instance buffer as the gl_instanceID can't be used in bgfx's glsl with D3D9.
- What cell the current vertex is in, this information could be baked in the vertex data as the grid layout does not change accros block.

At this moment the hurdle is to get the LNDCell to the shader.

The solutions tried in #615 should be dropped as if we are to use a texture binding to make the LNDCell allow to get information for a more precise altitude (in the PR screenshot the point are a little lower than they are now)

**Comment by bwrsandman** [comment]
Sampling a height map from a texture is not difficult but the issue is that we will need to properly rotate triangles within a quad in order for the diagonal edges to flow with the topology
![image](https://github.com/openblack/openblack/assets/1013356/a5f3b10d-ab0b-4e9b-9982-cdd75de1964c)

**Comment by bwrsandman** [comment]
Keep in mind that if you replace mesh data with texture data (such as height map, weight map, material id maps, light level maps and water alpha maps), you might introduce worse performance due to all these memory fetch instructions that can be very expensive.

**Comment by bwrsandman** [comment]
Since terrain is mostly static, you can also bake in the albedo, specular and geometry. This would be the most efficient but also the less maintainable for this early part of the project.

What I mean is that optimizing this here would improve runtime for sure but it will make hacking and making modifications more difficult.
