### ISSUE TITLE
Weird error on any Linux Release or Debug builds

### ISSUE THREAD

**Issue by pjduplooygis** [openblack/openblack#814]
Hi.

I get the following error on using openblack for Linux:

terminate called after throwing an instance of 'std::runtime_error'
what():  File Audio not found
Aborted (core dumped)

I have used the Ubuntu 24 Release and Debug builds, the standard Linux build, as well as running openblack with wine.

My install is Linux Mint based on Ubuntu 24.04.

Openblack is running fine on my Windows machine though.  (I used the same installer files).

Any help would be appreciated.

**Comment by bwrsandman** [comment]
If possible, can you post the debug build's logs?

**Comment by pjduplooygis** [comment]
[aa.txt](https://github.com/user-attachments/files/17186021/aa.txt)

Its over 4000 lines!!

**Comment by bwrsandman** [comment]
I don't see much in the log. Are you using the patched game files?
Is it exactly the same game asset directory as in windows?
What's the output of `ls path/to/you/game/directory/`?

**Comment by pjduplooygis** [comment]
Hi.  Sorted.  There was no Audio folder in my BNW folder.  Added it, and it works.  Thanks for the hint.  I am pretty sure the instructions said only to add Data and Scripts.

Please mark as solved.

Thank you sooo much

**Comment by bwrsandman** [comment]
Audio is fairly new. If there are instructions saying that. They're out of date.

**Comment by bwrsandman** [comment]
Updated the Readme. Thanks for bringing that to my attention.
