### ISSUE TITLE
L3D Mesh Implementation

### ISSUE THREAD

**Issue by handsomematt** [openblack/openblack#9]
Currently we're able to load in basic L3D models, not in a very clean way though. Adding support for skinned meshes and handling bone matrices and animations should include cleaning up code for non-skinned meshes too.

Skinned Meshes need to:
- [x] Load a skinned mesh in from an L3D file.
- [x] Read and apply bone matricies on the mesh in shader.
- [ ] Load a skinned mesh in from the mesh pack.
- [ ] Use the animations from the animation pack to adjust matrix transforms.

**Comment by bwrsandman** [comment]
This is all done with #225
