### ISSUE TITLE
Isn't std::unique_ptr preferred here?

### ISSUE THREAD

**Issue by skyrpex** [openblack/openblack#91]
https://github.com/openblack/openblack/blob/e7fe4a7f11ce2a55824bb99e7946dbe4ef6bf4cb/src/Graphics/Mesh.h#L68

It's been ages since coded C++ last time and I'm new to this repository, but seems that `_vertexBuffer` is owned by just the mesh (even the getter for that variable isn't used anywhere). In that case, I believe that `std::unique_ptr` is what should be used here. Less cycles will be spent in reference counting.

**Comment by handsomematt** [comment]
fixed 💯
